language: python
jobs:
  include:
    - os: linux
      dist: focal
      python: 3.9
    - os: linux
      dist: focal
      python: 3.8
    - os: linux
      dist: bionic
      python: 3.9
    - os: linux
      dist: bionic
      python: 3.8
    - os: linux
      dist: bionic
      python: 3.7
    - os: linux
      dist: bionic
      python: 3.6
    - os: osx
      # macOS 10.15.7
      osx_image: xcode12.2
    - os: osx
      # macOS 10.15.5
      osx_image: xcode11.6
    - os: osx
      # macOS 10.15.4
      osx_image: xcode11.5
    - os: osx
      # macOS 10.14.6
      osx_image: xcode11.3
    - os: osx
      # macOS 10.14.4
      osx_image: xcode10.3
    - os: osx
      # macOS 10.14
      osx_image: xcode10.2
# Test for multiple Python versions!
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# Install required packages for both production & testing
install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install -r requirements_test.txt
script:
  - find . -name "*.py" -exec pylint {} + || travis_terminate 1
  - coverage run test/test_main.py || travis_terminate 1
# Print coverage stats & push the results back to codecov
after_success:
  - coverage report
  - codecov
