language: python
# Test for multiple Python versions!
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# Install required packages for both production & testing
install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install -r requirements_test.txt
script:
  - find . -name "*.py" -exec pylint {} +
  - coverage run test/test_main.py
# Print coverage stats & push the results back to codecov
after_success:
  - coverage report
  - codecov
