language: python
# Test for multiple Python versions on several OSes!
jobs:
  include:
    - os: linux
      dist: focal
      python: 3.9
    - os: linux
      dist: focal
      python: 3.8
    - os: linux
      dist: bionic
      python: 3.9
    - os: linux
      dist: bionic
      python: 3.8
    - os: linux
      dist: bionic
      python: 3.7
    - os: linux
      dist: bionic
      python: 3.6
    - os: osx
      # macOS 10.15.7
      osx_image: xcode12.2
      language: generic
      env: PYTHON=3.9
    - os: osx
      # macOS 10.15.7
      osx_image: xcode12.2
      language: generic
      env: PYTHON=3.8
    - os: osx
      # macOS 10.15.7
      osx_image: xcode12.2
      language: generic
      env: PYTHON=3.7
    - os: osx
      # macOS 10.15.7
      osx_image: xcode12.2
      language: generic
      env: PYTHON=3.6
    - os: osx
      # macOS 10.14.6
      osx_image: xcode11.3
      language: generic
      env: PYTHON=3.9
    - os: osx
      # macOS 10.14.6
      osx_image: xcode11.3
      language: generic
      env: PYTHON=3.8
    - os: osx
      # macOS 10.14.6
      osx_image: xcode11.3
      language: generic
      env: PYTHON=3.7
    - os: osx
      # macOS 10.14.6
      osx_image: xcode11.3
      language: generic
      env: PYTHON=3.6
# Take care of requirements even before the installation step
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install python@${PYTHON};
    fi
# Install required packages for both production & testing
install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install -r requirements_test.txt
script:
  - find . -name "*.py" -exec pylint {} + || travis_terminate 1
  - coverage run test/test_main.py || travis_terminate 1
# Print coverage stats & push the results back to codecov
after_success:
  - coverage report
  - codecov
